# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartament',
            name='author',
        ),
        migrations.AddField(
            model_name='apartament',
            name='address',
            field=models.TextField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='apartament',
            name='availlability',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='apartament',
            name='end_reservation',
            field=models.DateTimeField(max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='apartament',
            name='start_reservation',
            field=models.DateTimeField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='apartament',
            name='description',
            field=models.TextField(blank=True, max_length=25000, unique=True),
        ),
        migrations.AlterField(
            model_name='apartament',
            name='title',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
