DROP DATABASE IF EXISTS `mydb`;
CREATE DATABASE `mydb`
    DEFAULT CHARACTER SET utf8
    DEFAULT COLLATE utf8_general_ci;

USE 'mysql';
GRANT ALL PRIVILEGES ON mydb.* TO 'xyz'@'localhost' IDENTIFIED BY 'test123'

WITH GRANT OPTION;
FLUSH PRIVILEGES;